spring.application.name=back-end

spring.datasource.url=jdbc:postgresql://localhost:5432/back_projeto_integrador
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.apache.hc.client5.http=DEBUG