@startuml

skinparam componentStyle rectangle
skinparam backgroundColor white

package "Frontend (React)" {

    [Dashboard]
    [BuscaEdital]
    [AlertasView]
}

package "Backend (Spring Boot)" {

    package "Controllers" {
        [ClientesController]
        [PropostasController]
        [EditalController]
        [AuthController]
    }

    package "Services" {
        [PropostasService]
        [ClientesService]
        [DailySearch]
        [EditalService]
    }

    package "Repositories" {
        [PropostasRepository]
        [ClienteRepository]
        [EditalRepository]
    }
}

database "PostgreSQL" as DB

[APIPNCP] <<external>>

Dashboard --> PropostasController : REST
BuscaEdital --> PropostasController : REST
AlertasView --> ClientesController : REST

PropostasController --> PropostasService
ClientesController --> ClientesService
EditalController --> EditalService

ClientesService --> ClienteRepository
PropostasService --> PropostasRepository
EditalService --> EditalRepository

DailySearch --> PropostasRepository

PropostasService --> APIPNCP : API REST
DailySearch --> APIPNCP : API REST

PropostasRepository --> DB
ClienteRepository --> DB
EditalRepository --> DB

@enduml
